name: Build TomaScript

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with libXenon
        run: |
          docker run --rm \
            -v "$PWD:/app" \
            -w /app \
            free60/libxenon:latest \
            bash -lc 'make'

      - name: Upload build files
        uses: actions/upload-artifact@v4
        with:
          name: TomaScript-build
          path: |
            *.elf
            *.elf32
